# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "yii2"
  # config.vm.box_check_update = false

   config.vm.network "forwarded_port", guest: 80, host: 4568
   config.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"

  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
    config.vm.network "public_network", ip: "192.168.0.96"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # config.vm.synced_folder "../data", "/vagrant_data"
   config.vm.synced_folder "./html", "/var/www/html", id: "vagrant-root",
    :owner => "vagrant",
    :group => "www-data",
    mount_options: ["dmode=775,fmode=664"]

  #config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    # vb.gui = true
  
     # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
#   end

end